dotenv: .env
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink@1.8.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink@1.8.1'
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  goerli:
    eth_usd_pricefeed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
  goerli-fork:
    eth_usd_pricefeed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
  mainnet-fork-dev:
    eth_usd_pricefeed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
    max_fee: 7656250000
